// Narrative and shot directions authored by Claude Sonnet 5; see docs/SONNET_SCRIPT.md.
export type HeroId = 'kane' | 'jinx' | 'bull';
export interface StoryPage { speaker: string; text: string; portrait?: string; visual?: string; seconds?: number }
export interface StoryBeat { id: string; title: string; pages: StoryPage[]; cinematic?: boolean }
export const HERO_STORIES: Record<HeroId, {tagline:string;secret:string;want:string}> = {"kane": {"tagline": "BALANCED BRAWLER", "secret": "Used to work security for men like Korvo. Quit when the job stopped being about safety and started being about leverage. Fights clean, talks less, finishes what he starts.", "want": "Used to work security for men like Korvo. Quit when the job stopped being about safety and started being about leverage. Fights clean, talks less, finishes what he starts."}, "jinx": {"tagline": "FAST COURIER", "secret": "Runs the district's back routes faster than anyone alive or dead. Doesn't care about Korvo's politics \u2014 cares that half her regular stops just went dark. Fixes that the direct way.", "want": "Runs the district's back routes faster than anyone alive or dead. Doesn't care about Korvo's politics \u2014 cares that half her regular stops just went dark. Fixes that the direct way."}, "bull": {"tagline": "HEAVY FIGHTER", "secret": "Was here the night the reactor lit the sky orange. Never left. The district raised him after that; he's not about to watch Korvo starve it for spare change.", "want": "Was here the night the reactor lit the sky orange. Never left. The district raised him after that; he's not about to watch Korvo starve it for spare change."}};
export function opening(hero:HeroId, _coop:boolean):StoryBeat { return {id:"opening",title:"LIGHTS OUT",cinematic:true,pages:[{speaker:"NEON WARD",text:"THE DISTRICT WENT DARK LAST NIGHT.",portrait:hero,visual:"outage",seconds:4},{speaker:hero.toUpperCase(),text:"Korvo pulls the plug, everybody pays. Not tonight.",portrait:hero,visual:"entrance",seconds:4},{speaker:"PUNK",text:"Turn around. Korvo's collecting.",portrait:hero,visual:"blockade",seconds:3}]}; }
export function midpoint(hero:HeroId):StoryBeat { return {id:"midpoint",title:"THE CORE",cinematic:true,pages:[{speaker:"KORVO",text:"Break me, or stay dark forever.",portrait:hero,visual:"core",seconds:5}]}; }
export function ending(hero:HeroId):StoryBeat { return {id:"back-on",title:"BACK ON",cinematic:true,pages:[{speaker:"NEON WARD",text:"CORE ONLINE. THE DISTRICT LIGHTS UP.",portrait:hero,visual:"restart",seconds:3},{speaker:hero.toUpperCase(),text:"Korvo's out of the dark. Drinks are on him.",portrait:hero,visual:"marquee",seconds:4}]}; }
export const CASE_FILES: {id:string;title:string;unlock:number;pages:StoryPage[]}[] = [{"id": "neon-0", "title": "THE BLACKOUT PROTOCOL", "unlock": 0, "pages": [{"speaker": "THE BLACKOUT PROTOCOL", "text": "Korvo's crews cut a block's feed, wait a week, then offer to \"restore priority service\" for a fee. Most blocks pay by day three."}]}, {"id": "neon-1", "title": "THE CORE", "unlock": 1, "pages": [{"speaker": "THE CORE", "text": "Salvaged reactor-adjacent hardware from the fallout years, retrofitted to run the district grid. Nobody's supposed to own one privately. Korvo does."}]}, {"id": "neon-2", "title": "NEON WARD", "unlock": 2, "pages": [{"speaker": "NEON WARD", "text": "Years after the fallout, some residents came back changed \u2014 thicker skin, stranger reflexes, no complaints. The district stopped asking questions before it started asking for I.D."}]}, {"id": "neon-3", "title": "KORVO'S RISE", "unlock": 3, "pages": [{"speaker": "KORVO'S RISE", "text": "He didn't build the district. He just bought the one thing that could turn it off."}]}, {"id": "neon-4", "title": "VESPER", "unlock": 4, "pages": [{"speaker": "VESPER", "text": "The drug of choice once the lights are back on: a shimmer-pink haze that shows up in every club window from Fifth to the Row. Nobody in the district asks what's in it, only who's pouring."}]}, {"id": "korvo", "title": "KORVO", "unlock": 5, "pages": [{"speaker": "KORVO", "text": "Built his empire on scarcity, not product. Doesn't sell power \u2014 sells the absence of it, one district at a time, to whoever's desperate enough to keep paying.", "portrait": "korvo"}]}];
